development:
  open_registration_date: 2011-12-12 11:12:0
  max_attendees: 150

test:
  open_registration_date: 2011-12-12 11:12:0
  max_attendees: 150
  
production:
  open_registration_date: 2011-12-12 11:12:0
  max_attendees: 150