development:
  host: localhost
  database: conf_oo_development

test:
  host: localhost
  database: conf_oo_test

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOHQ_URL'] %>
  port: <%= ENV['MONGOHQ_PORT'] %>
  username: <%= ENV['MONGOHQ_USERNAME'] %>
  password: <%= ENV['MONGOHQ_PASSWORD'] %>
  database: <%= ENV['MONGOHQ_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
